import uuid
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session

from app.db.base_class import Base
from app.models.cities import City
from app.schemas.cities import CityCreate, CityUpdate
from app.repositories.cities_repo import CityRepository


@pytest.fixture(scope="function")
def db_session() -> Session:
    """Create a clean in-memory database for each test."""
    engine = create_engine("sqlite:///:memory:", connect_args={"check_same_thread": False})
    # Create only the required tables for City tests
    City.__table__.create(bind=engine)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    session = SessionLocal()
    try:
        yield session
    finally:
        session.close()


@pytest.fixture
def repo(db_session: Session) -> CityRepository:
    """Fixture to provide a CityRepository instance."""
    return CityRepository(db_session)


def test_create_city(repo: CityRepository):
    """Test creating a new city."""
    city_in = CityCreate(
        name="Karachi",
        country="Pakistan",
        center_point="24.8607,67.0011",
        is_active=True
    )
    city = repo.create(city_in)

    assert city.id is not None
    assert city.name == "Karachi"
    assert city.country == "Pakistan"
    assert city.centerPoint == "24.8607,67.0011"
    assert city.isActive is True
    assert city.slug == "karachi"  # Auto-generated by schema


def test_get_city(repo: CityRepository):
    """Test fetching a city by ID."""
    city_in = CityCreate(name="Lahore", country="Pakistan")
    created = repo.create(city_in)

    fetched = repo.get(created.id)
    assert fetched is not None
    assert fetched.id == created.id
    assert fetched.name == "Lahore"


def test_get_city_not_found(repo: CityRepository):
    """Test fetching a non-existent city."""
    random_id = uuid.uuid4()
    fetched = repo.get(random_id)
    assert fetched is None


def test_get_by_slug(repo: CityRepository):
    """Test fetching a city by slug."""
    city_in = CityCreate(name="Islamabad", country="Pakistan", slug="isloo")
    created = repo.create(city_in)

    fetched = repo.get_by_slug("isloo")
    assert fetched is not None
    assert fetched.id == created.id
    assert fetched.slug == "isloo"


def test_get_by_name_and_country(repo: CityRepository):
    """Test fetching a city by name and country."""
    city_in = CityCreate(name="New York", country="USA")
    created = repo.create(city_in)

    fetched = repo.get_by_name_and_country("New York", "USA")
    assert fetched is not None
    assert fetched.id == created.id


def test_get_all(repo: CityRepository):
    """Test fetching a paginated list of cities."""
    # Create 3 cities
    for i in range(3):
        repo.create(CityCreate(name=f"City {i}", country="Test Country"))

    all_cities = repo.get_all(skip=0, limit=10)
    assert len(all_cities) == 3

    paginated = repo.get_all(skip=1, limit=1)
    assert len(paginated) == 1
    assert paginated[0].name == "City 1"


def test_update_city(repo: CityRepository):
    """Test updating an existing city."""
    created = repo.create(CityCreate(name="Old City", country="Old Country"))
    
    update_in = CityUpdate(name="New City", is_active=False)
    updated = repo.update(created, update_in)

    assert updated.name == "New City"
    assert updated.isActive is False
    assert updated.country == "Old Country"


def test_delete_city(repo: CityRepository):
    """Test deleting a city."""
    created = repo.create(CityCreate(name="To Delete", country="DeleteLand"))
    city_id = created.id

    repo.delete(created)
    
    fetched = repo.get(city_id)
    assert fetched is None
