"""Add location-based fields to Profile (multi-dialect fix)

Revision ID: 2957d90ecca4
Revises: 
Create Date: 2026-03-03 18:50:57.493476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2957d90ecca4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    # ### commands auto generated by Alembic - please adjust! ###
    
    # We skip ID type changes on SQLite because it already handles UUIDs as text 
    # and trying to batch-alter with CAST to UUID causes integrity errors.
    if not is_sqlite:
        with op.batch_alter_table('cities', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)

        with op.batch_alter_table('listing_media', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('listingId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)

        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('listingId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('buyerId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('sellerId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)

        with op.batch_alter_table('posts', schema=None) as batch_op:
            batch_op.alter_column('owner_id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if not is_sqlite:
            batch_op.alter_column('userId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
        
        # Adjusting location fields to be standard Strings on SQLite
        batch_op.alter_column('last_location_point',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('default_location_point',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        
        # Handle case where indices might not exist
        try:
            batch_op.drop_index(batch_op.f('idx_profiles_default_location_point'))
        except: pass
        try:
            batch_op.drop_index(batch_op.f('idx_profiles_last_location_point'))
        except: pass

    if not is_sqlite:
        with op.batch_alter_table('reviews', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('orderId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('reviewerId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('reviewedUserId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)

        with op.batch_alter_table('service_listings', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('sellerId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)
            batch_op.alter_column('cityId',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=True)

        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('id',
                existing_type=sa.NUMERIC(),
                type_=sa.UUID(),
                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('service_listings', schema=None) as batch_op:
        batch_op.alter_column('cityId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('sellerId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('reviewedUserId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('reviewerId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('orderId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_profiles_last_location_point'), ['last_location_point'], unique=False)
        batch_op.create_index(batch_op.f('idx_profiles_default_location_point'), ['default_location_point'], unique=False)
        batch_op.alter_column('default_location_point',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('last_location_point',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('userId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('sellerId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('buyerId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('listingId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('listing_media', schema=None) as batch_op:
        batch_op.alter_column('listingId',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
