"""Add user_device_tokens table

Revision ID: 3af94274cd19
Revises: 4340c8e4afc8
Create Date: 2026-04-28 17:34:51.192329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af94274cd19'
down_revision: Union[str, Sequence[str], None] = '4340c8e4afc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('expo_push_token', sa.String(length=500), nullable=False),
    sa.Column('deviceType', sa.String(length=50), nullable=False),
    sa.Column('deviceName', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('lastUsedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_device_tokens_expo_push_token'), 'user_device_tokens', ['expo_push_token'], unique=True)
    op.create_index(op.f('ix_user_device_tokens_id'), 'user_device_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_device_tokens_userId'), 'user_device_tokens', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_device_tokens_userId'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_id'), table_name='user_device_tokens')
    op.drop_index(op.f('ix_user_device_tokens_expo_push_token'), table_name='user_device_tokens')
    op.drop_table('user_device_tokens')
    # ### end Alembic commands ###
