"""modernize_models_and_add_timestamps

Revision ID: 4340c8e4afc8
Revises: b7a1d4f6e9c2
Create Date: 2026-04-09 18:02:48.570346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4340c8e4afc8'
down_revision: Union[str, Sequence[str], None] = 'b7a1d4f6e9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. New Timestamps for tables that didn't have them
    for table in ['categories', 'cities']:
        op.add_column(table, sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        op.add_column(table, sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    op.create_index(op.f('ix_cities_country'), 'cities', ['country'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)

    # 2. Rename existing createdAt/updatedAt to created_at/updated_at and add missing updated_at
    # listing_media
    op.alter_column('listing_media', 'createdAt', new_column_name='created_at')
    op.add_column('listing_media', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # notifications
    op.alter_column('notifications', 'createdAt', new_column_name='created_at')
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # orders
    op.alter_column('orders', 'createdAt', new_column_name='created_at')
    op.alter_column('orders', 'updatedAt', new_column_name='updated_at')
    
    # otp_tokens
    op.add_column('otp_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # profiles
    op.alter_column('profiles', 'createdAt', new_column_name='created_at')
    op.alter_column('profiles', 'updatedAt', new_column_name='updated_at')
    
    # refresh_tokens
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # reviews
    op.alter_column('reviews', 'createdAt', new_column_name='created_at')
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    # service_listings
    op.alter_column('service_listings', 'createdAt', new_column_name='created_at')
    op.alter_column('service_listings', 'updatedAt', new_column_name='updated_at')

    # 3. User Index Update
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])

    # service_listings
    op.alter_column('service_listings', 'updated_at', new_column_name='updatedAt')
    op.alter_column('service_listings', 'created_at', new_column_name='createdAt')
    
    # reviews
    op.drop_column('reviews', 'updated_at')
    op.alter_column('reviews', 'created_at', new_column_name='createdAt')
    
    # refresh_tokens
    op.drop_column('refresh_tokens', 'updated_at')
    
    # profiles
    op.alter_column('profiles', 'updated_at', new_column_name='updatedAt')
    op.alter_column('profiles', 'created_at', new_column_name='createdAt')
    
    # otp_tokens
    op.drop_column('otp_tokens', 'updated_at')

    # orders
    op.alter_column('orders', 'updated_at', new_column_name='updatedAt')
    op.alter_column('orders', 'created_at', new_column_name='createdAt')

    # notifications
    op.drop_column('notifications', 'updated_at')
    op.alter_column('notifications', 'created_at', new_column_name='createdAt')

    # listing_media
    op.drop_column('listing_media', 'updated_at')
    op.alter_column('listing_media', 'created_at', new_column_name='createdAt')

    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_country'), table_name='cities')
    op.drop_column('cities', 'updated_at')
    op.drop_column('cities', 'created_at')

    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
