"""add_photo_cloudinary_public_id_to_profiles

Revision ID: 4cdff27176e5
Revises: 4d5f96ffb82f
Create Date: 2026-03-06 01:46:40.382980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdff27176e5'
down_revision: Union[str, Sequence[str], None] = '4d5f96ffb82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('photoCloudinaryPublicId', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'photoCloudinaryPublicId')
    # ### end Alembic commands ###
