"""remove_user_name_and_refine_filters

Revision ID: c4e1e3dbbfdf
Revises: 2957d90ecca4
Create Date: 2026-03-05 01:35:25.898559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e1e3dbbfdf'
down_revision: Union[str, Sequence[str], None] = '2957d90ecca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_service_listings_service_location', 'service_listings', ['service_location'], unique=False, postgresql_using='gist')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index('idx_service_listings_service_location', table_name='service_listings', postgresql_using='gist')
    # ### end Alembic commands ###
