"""create_uuid_category_and_listings

Revision ID: c72afac2c3e4
Revises: d864e7f8ba7a
Create Date: 2026-03-09 20:54:47.389370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c72afac2c3e4'
down_revision: Union[str, Sequence[str], None] = 'd864e7f8ba7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_categories_parent_id_name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('service_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sellerId', sa.UUID(), nullable=False),
    sa.Column('cityId', sa.UUID(), nullable=True),
    sa.Column('categoryId', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priceType', sa.String(length=20), server_default=sa.text("'fixed'"), nullable=False),
    sa.Column('priceAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('isNegotiable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('serviceLocation', sa.String(length=255), nullable=False),
    sa.Column('serviceRadiusKm', sa.Float(), nullable=False),
    sa.Column('service_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cityId'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sellerId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'description', name='uq_service_listings_title_description')
    )
    op.create_index('idx_service_listings_service_location', 'service_listings', ['service_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_service_listings_categoryId'), 'service_listings', ['categoryId'], unique=False)
    op.create_index(op.f('ix_service_listings_cityId'), 'service_listings', ['cityId'], unique=False)
    op.create_index(op.f('ix_service_listings_id'), 'service_listings', ['id'], unique=False)
    op.create_index(op.f('ix_service_listings_sellerId'), 'service_listings', ['sellerId'], unique=False)
    op.create_index(op.f('ix_service_listings_status'), 'service_listings', ['status'], unique=False)
    op.create_index(op.f('ix_service_listings_title'), 'service_listings', ['title'], unique=False)
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.create_foreign_key(None, 'listing_media', 'service_listings', ['listingId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'service_listings', ['listingId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'service_listings', ['listingId'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'listing_media', type_='foreignkey')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('posts_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_service_listings_title'), table_name='service_listings')
    op.drop_index(op.f('ix_service_listings_status'), table_name='service_listings')
    op.drop_index(op.f('ix_service_listings_sellerId'), table_name='service_listings')
    op.drop_index(op.f('ix_service_listings_id'), table_name='service_listings')
    op.drop_index(op.f('ix_service_listings_cityId'), table_name='service_listings')
    op.drop_index(op.f('ix_service_listings_categoryId'), table_name='service_listings')
    op.drop_index('idx_service_listings_service_location', table_name='service_listings', postgresql_using='gist')
    op.drop_table('service_listings')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
